language: node_js
node_js:
  - '9'
branches:
  only:
    - production
    - master
git:
  depth: 3
script:
  -  if [ "$TRAVIS_EVENT_TYPE" == "push" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
     npx serverless deploy;
     fi

  -  if [ "$TRAVIS_EVENT_TYPE" == "push" ] && [ "$TRAVIS_BRANCH" == "production" ]; then
     npx serverless deploy -v -s prod;
     fi
