service: beeline-frontend-proxy

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: ap-southeast-1
  stage: staging
  runtime: nodejs6.10
  memorySize: 128
  environment:
    BACKEND_URL: http://app-pages.beeline.sg
    ROBOTS_URL: https://api.beeline.sg

functions:
  lambda:
    handler: src/lambda.handler
    timeout: 30
    cors: true
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
